# 베이스 이미지
FROM openjdk:11
# 작성자 라벨 설정
LABEL maintainer "kh<kh@iei.com>"
# 버전 라벨 생성
LABEL version="1.0"
# 컨테이너에 /root 디렉터리에 빌드 컨텍스트 안에 있는 ~.jar 파일을 카피하겠다.
COPY 05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar /root
# 명령어 수행시킬 때 외부로부터 값을 도커파일 내부로 전달 받을 때 사용하는 명령어 (SCOPE : 파일 내부)
# 내부로부터 값을 전달 받을 수 있는 PORT 변수를 선언 (기본 값 : 8088)
ARG PORT=8088
# 내부로부터 값을 전달 받을 수 있는 PROFILE 변수를 선언 (기본 값 : dev)
ARG PROFILE=dev
# 타임존 설정
ENV TZ=Asia/Seoul
# 환경변수 : 외부로부터 받아온 값을 ENV로 넘겨준다.
ENV PROFILE_ENV=${PROFILE}
# /root 디렉토리로 작업 디렉터리를 바꾼다. 프롬프트가 /root로 이동되면서 작업 디렉터리가 됨
WORKDIR /root
# 실행
RUN pwd
RUN ["echo", "hello"]
# 포트 노출
EXPOSE ${PORT}
# 처음 실행할 명령어 지정
CMD ["java", "-jar", "05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=${PROFILE_ENV}"]